[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; img-src 'self' data: https:; font-src 'self' https:;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "http://eventzbytwinkle.com/*"
  to = "https://eventzbytwinkle.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.eventzbytwinkle.com/*"
  to = "https://www.eventzbytwinkle.com/:splat"
  status = 301
  force = true